"""empty message

Revision ID: 327cee236be3
Revises: a951d14c3dca
Create Date: 2020-06-12 13:02:44.812898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327cee236be3'
down_revision = 'a951d14c3dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('los', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'los', 'courses', ['course_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'los', type_='foreignkey')
    op.drop_column('los', 'course_id')
    # ### end Alembic commands ###
