"""empty message

Revision ID: 4fe5429f8a2e
Revises: ce6ad343ae33
Create Date: 2020-06-12 14:10:33.391854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe5429f8a2e'
down_revision = 'ce6ad343ae33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('los', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'los', 'courses', ['course_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'los', type_='foreignkey')
    op.drop_column('los', 'course_id')
    # ### end Alembic commands ###
