"""empty message

Revision ID: 63147400c56a
Revises: c2da27bd33cf
Create Date: 2020-07-02 19:47:16.144069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63147400c56a'
down_revision = 'c2da27bd33cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_user_id_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'course_users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_user_id_fkey', 'courses', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
