"""empty message

Revision ID: 7f948701e409
Revises: 0e1fa16c5262
Create Date: 2020-07-02 19:58:38.281520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f948701e409'
down_revision = '0e1fa16c5262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'user_id')
    # ### end Alembic commands ###
