"""empty message

Revision ID: aa06513bb722
Revises: 3a0f58cb718e
Create Date: 2020-05-27 14:05:56.398106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa06513bb722'
down_revision = '3a0f58cb718e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lis', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
