"""empty message

Revision ID: bc067eac7008
Revises: 73f9d45f9077
Create Date: 2020-05-30 20:28:00.370918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc067eac7008'
down_revision = '73f9d45f9077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_out_KSAT_name_key', 'courses', type_='unique')
    op.drop_constraint('courses_req_KSAT_name_key', 'courses', type_='unique')
    op.drop_column('courses', 'out_KSAT_name')
    op.drop_column('courses', 'req_KSAT_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('req_KSAT_name', sa.VARCHAR(length=400), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('out_KSAT_name', sa.VARCHAR(length=400), autoincrement=False, nullable=False))
    op.create_unique_constraint('courses_req_KSAT_name_key', 'courses', ['req_KSAT_name'])
    op.create_unique_constraint('courses_out_KSAT_name_key', 'courses', ['out_KSAT_name'])
    # ### end Alembic commands ###
