"""empty message

Revision ID: ce6ad343ae33
Revises: 327cee236be3
Create Date: 2020-06-12 13:16:22.115752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6ad343ae33'
down_revision = '327cee236be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('los_course_id_fkey', 'los', type_='foreignkey')
    op.drop_column('los', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('los', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('los_course_id_fkey', 'los', 'courses', ['course_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
