"""empty message

Revision ID: e1ea47b6dde3
Revises: eda182a8f1c5
Create Date: 2020-06-12 19:43:50.738973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ea47b6dde3'
down_revision = 'eda182a8f1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ksats', sa.Column('lo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ksats', 'los', ['lo_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('los_out_KSAT_name_key', 'los', type_='unique')
    op.drop_constraint('los_req_KSAT_name_key', 'los', type_='unique')
    op.drop_column('los', 'req_KSAT_name')
    op.drop_column('los', 'out_KSAT_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('los', sa.Column('out_KSAT_name', sa.VARCHAR(length=400), autoincrement=False, nullable=False))
    op.add_column('los', sa.Column('req_KSAT_name', sa.VARCHAR(length=400), autoincrement=False, nullable=False))
    op.create_unique_constraint('los_req_KSAT_name_key', 'los', ['req_KSAT_name'])
    op.create_unique_constraint('los_out_KSAT_name_key', 'los', ['out_KSAT_name'])
    op.drop_constraint(None, 'ksats', type_='foreignkey')
    op.drop_column('ksats', 'lo_id')
    # ### end Alembic commands ###
