"""empty message

Revision ID: e6aa00fe617b
Revises: e1ea47b6dde3
Create Date: 2020-06-18 20:25:15.845730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6aa00fe617b'
down_revision = 'e1ea47b6dde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialists', 'ksat_ids')
    op.drop_constraint('work_roles_category_id_fkey', 'work_roles', type_='foreignkey')
    op.drop_column('work_roles', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_roles', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('work_roles_category_id_fkey', 'work_roles', 'categories', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('specialists', sa.Column('ksat_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
